# Generated by Django 4.0.3 on 2022-03-29 15:05

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=30, region=None, verbose_name='phone number')),
                ('about_me', models.TextField(null=True, verbose_name='about me')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=20, verbose_name='gender')),
                ('country', django_countries.fields.CountryField(default='RU', max_length=2, verbose_name='country')),
                ('city', models.CharField(max_length=180, verbose_name='city')),
                ('license', models.CharField(blank=True, max_length=20, null=True, verbose_name='property license')),
                ('profile_image', models.ImageField(default='/profile_example.png', upload_to='', verbose_name='profile image')),
                ('buyer', models.BooleanField(default=False, help_text='do you want to buy a property?', verbose_name='buyer')),
                ('seller', models.BooleanField(default=False, help_text='do you want to sell a property?', verbose_name='seller')),
                ('agent', models.BooleanField(default=False, help_text='are you an agent?', verbose_name='agent')),
                ('top_agent', models.BooleanField(default=False, verbose_name='top agent')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('count_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='number of reviews')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
