# Generated by Django 4.0.3 on 2022-03-31 17:28

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='ownership')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('ref_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='link to properties')),
                ('description', models.TextField(default='', null=True, verbose_name='description')),
                ('country', django_countries.fields.CountryField(default='RU', max_length=2, verbose_name='country')),
                ('city', models.CharField(default='Saint-Petersburg', max_length=180, verbose_name='city')),
                ('postal_code', models.CharField(default='000000', max_length=100, verbose_name='postal code')),
                ('property_street', models.CharField(default='', max_length=150, verbose_name='property_street')),
                ('property_number', models.IntegerField(default=123, validators=[django.core.validators.MinValueValidator(1)], verbose_name='property number')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='price')),
                ('property_tax', models.DecimalField(decimal_places=2, default=0.15, help_text='property tax is charged in the amount of 15%', max_digits=6, verbose_name='property tax')),
                ('plot_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='plot area (m^2)')),
                ('number_of_floors', models.IntegerField(default=0, verbose_name='number of floors')),
                ('bedrooms', models.IntegerField(default=1, verbose_name='bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='bathrooms')),
                ('advert_type', models.CharField(choices=[('sale', 'sale'), ('rent', 'rent'), ('auction', 'auction')], default='sale', max_length=50, verbose_name='advert type')),
                ('property_type', models.CharField(choices=[('house', 'house'), ('apartment', 'apartment'), ('commercial premises', 'commercial premises'), ('office', 'office'), ('warehouse', 'warehouse'), ('other', 'other')], default='other', max_length=50, verbose_name='property type')),
                ('main_photo', models.ImageField(blank=True, default='/property_main_example.jpg', null=True, upload_to='', verbose_name='main photo')),
                ('photo1', models.ImageField(blank=True, default='/property_example.jpg', null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, default='/property_example.jpg', null=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, default='/property_example.jpg', null=True, upload_to='')),
                ('photo4', models.ImageField(blank=True, default='/property_example.jpg', null=True, upload_to='')),
                ('published_status', models.BooleanField(default=False, verbose_name='published status')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='who are you? - agent, seller, buyer')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyViews',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=250, verbose_name='ip')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='properties.property')),
            ],
            options={
                'verbose_name': 'general views on real estate',
                'verbose_name_plural': 'general property views',
            },
        ),
    ]
